version: '3.3'
services:
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      SECRET_KEY: PLEASE ADD SECRET_KEY HERE!
    ports:
      - '8080:5000'
